### PR TITLE
ui. make speedtest popover closable

### PR DESCRIPTION
**Pull request by federicoballarini**
Added "Close" button for speedtest popup.
Refer to https://github.com/NethServer/dev/issues/6435

### CODE REVIEW

**Comment by gsanchietti** [comment]
This is a screenshot of the change:
Screenshot from 2021-02-22 09-22-10

The tooltip behavior is quite different from other tooltips around and the close button doesn't really fit well any known pattern.

**Review by gsanchietti — CHANGES_REQUESTED** [review]
The UI is too different from existing patterns.

**Comment by edospadoni** [comment]
Hi @federicoballarini as you cas see [here](https://www.patternfly.org/v3/pattern-library/widgets/#popover) you can add the "X" in the title of popover to close the tooltip.

**Comment by federicoballarini** [comment]
> Hi @federicoballarini as you cas see [here](https://www.patternfly.org/v3/pattern-library/widgets/#popover) you can add the "X" in the title of popover to close the tooltip.

Sorry @edospadoni. Can you link the row where the popover is initialized? Is not there: https://github.com/NethServer/nethserver-firewall-base/blob/0f40091a539003e4758914ba3b52b12a28ba8137/ui/src/views/WAN.vue#L2127 ?

**Comment by edospadoni** [comment]
> > Hi @federicoballarini as you cas see [here](https://www.patternfly.org/v3/pattern-library/widgets/#popover) you can add the "X" in the title of popover to close the tooltip.
> 
> Sorry @edospadoni. Can you link the row where the popover is initialized? Is not there:
> 
> https://github.com/NethServer/nethserver-firewall-base/blob/0f40091a539003e4758914ba3b52b12a28ba8137/ui/src/views/WAN.vue#L2127
> 
> ?

When the user click on "Speedtest" button, the code invoke [this](https://github.com/NethServer/nethserver-firewall-base/blob/0f40091a539003e4758914ba3b52b12a28ba8137/ui/src/views/WAN.vue#L2147) function. In this function on line [2157](https://github.com/NethServer/nethserver-firewall-base/blob/0f40091a539003e4758914ba3b52b12a28ba8137/ui/src/views/WAN.vue#L2157), there is the popover initialization. On line [2178](https://github.com/NethServer/nethserver-firewall-base/blob/0f40091a539003e4758914ba3b52b12a28ba8137/ui/src/views/WAN.vue#L2178) the popover body is drawn with `popover.options.content` definition

**Comment by federicoballarini** [comment]
I tried to change the code but I couldn't find a workable solution. I think I need an help :)

**Comment by gsanchietti** [comment]
@stephdl would you give it some help since you've implemented the feature?

**Comment by stephdl** [comment]
obviously I can help but I thought I was the father of the nethgui widget, not this one :)

**Comment by stephdl** [comment]
> The UI is too different from existing patterns.

if we put a cancel button on the left and a save button on the right it matchs the pattern we have on modal, do I am wrong 

Screenshot (80)

**Comment by stephdl** [comment]
we are in a popover, not easy to add a button with class='close' in the header, I would like to propose you add

```
            setTimeout(function() {
              $("#use_settings").click(function() {
                setSpeedValues(
                  context.$options.filters.sanitize(iface.name),
                  Math.round(success.download / 1024),
                  Math.round(success.upload / 1024)
                );
+                popover.hide();
              });
```
like this when you save we close the popover

and you move the buton on the right first `close`, second `save`

I think we have a relevant pattern

**Comment by gsanchietti** [comment]
The close button is not a good pattern here because we are working more on a popover than on a dialog.
But we can't find a better way ...

**Comment by federicoballarini** [comment]
I wait for instructions :D

**Comment by gsanchietti** [comment]
IMO we can have 2 alternative acceptable implementations:
- add an X (close) button on the popover title as Edoardo suggested
- or close the popup when clicking outside it, only if the speedtest is not running

**Comment by stephdl** [comment]
The suggestion I added close the pop over when you press 'use these settings'

**Comment by edospadoni** [comment]
> I wait for instructions :D

Have you tried to add `data-close="true"` below [this](https://github.com/NethServer/nethserver-firewall-base/blob/0f40091a539003e4758914ba3b52b12a28ba8137/ui/src/views/WAN.vue#L119) line?

**Comment by edospadoni** [comment]
> > > I wait for instructions :D
> > 
> > 
> > Have you tried to add `data-close="true"` below [this](https://github.com/NethServer/nethserver-firewall-base/blob/0f40091a539003e4758914ba3b52b12a28ba8137/ui/src/views/WAN.vue#L119) line?
> 
> Yes and it seems to not work... but I found out that "data-trigger": "focus" is working. How can apply it only when speedtest is finished? I tried setAttribute, but I get JS error.

Yes you are right. It seems that patternfly has removed support for the "X" button. In the example I linked above, `data-close="true"` is set but does not work. Then go ahead with the "Close" button inside the popover as the initial PR.

**Review by edospadoni — APPROVED** [review]

**Review by gsanchietti — APPROVED** [review]
If Edoardo approved, I'm ok with it.

Thank you Federico!

**Pull request merged**
