### PR TITLE
Restart speedtest each time needed

### PR DESCRIPTION
**Pull request by stephdl**
this PR intends to fix

- the multiple instances running at the same time
- a `/s` to the value of download/upload
- avoid to reload the web page if you want to make a new test

https://github.com/NethServer/dev/issues/6385

### CODE REVIEW

**Review by gsanchietti — CHANGES_REQUESTED** [review]
In my opinion, both "Server sponsor" and "Server ID" doesn't really offer a real value to the normal user.
What is the user supposed to do with them? The user should now the command line cli syntax to have relevant information from it.

If we want to expose extra info, it should be hidden by default.

**Comment by stephdl** [comment]
We are in a popover, we cannot display much informations and it is a pity because with the last version of speedtest-cli we could display the ISP, the external public IP, much information. However I came to the conclusion that could be a good new network tool, lets remove it for now

**Comment by stephdl** [comment]
speedtest-cli updated and available in nethserver-testing

http://packages.nethserver.org/nethserver/7.9.2009/testing/x86_64/Packages/speedtest-cli-2.1.2-1.ns7.noarch.rpm

**Review by gsanchietti — APPROVED** [review]
Seems good to me, but let's wait Edoardo approval about the JS part

**Review by edospadoni — APPROVED** [review]

**Pull request merged**
