### PR TITLE
api. always show IPv4 as current ip address

### PR DESCRIPTION
**Pull request by federicoballarini**
Refer to https://github.com/NethServer/dev/issues/6761

### CODE REVIEW

**Review by gsanchietti — COMMENTED** [review]
If the connectivity is IPv6 only, this will not fix the issue.

What is the aim of the PR? Fix the issue for IPv6 or always display and IPv4 address?

**Comment by federicoballarini** [comment]
I noticed this behaviour because one customer has changed connectivity and the provider offers both IPv4 and IPv6 networks.
If we don't set dig with -4 option, Cockpit shows a blank IP address (curl shows IPv6 one by default)

**Comment by gsanchietti** [comment]
So I'd go with a better solution using curl instead of dig so we are sure that it always works.

**Comment by federicoballarini** [comment]
> So I'd go with a better solution using curl instead of dig so we are sure that it always works.

But I think it's more useful to show the ipv4 for the sysadmin. What do you think to force always IPv4?

**Review by gsanchietti — APPROVED** [review]

**Pull request merged**
